### ISSUE TITLE
FF isn't compatible with mods that add biomes

### ISSUE THREAD

**Issue by SirChamomile** [Glitchfiend/FamiliarFauna#13]
I'm using the newest version of FF with the development version of Conquest Reforged for 1.12. As alluded to in the previous issue thread, FF doesn't spawn mobs using the forge biomes dictionary. As a result, there it is incompatible with CR. I guess this is pretty straightforward. Is there plans to allow more mod compatibility?

**Comment by Forstride** [comment]
I didn't want to use the biome dictionary cause you can't pick and choose individual biomes that way.  There's already an issue open about adding biome configurability for every mob, and ideally, i'd like to add defaults for popular biome-adding mods so people don't have to mess with configs.

I'm not sure what biomes Conquest Reforged even adds, cause at a first glance, it just looks like it adds new blocks, and their mod is closed source, so I can't look up the proper biome names.

**Comment by SirChamomile** [comment]
Thanks Forstride. The guys over there are adapting Conquest to survival. I have a feeling it's going to be in a lot of modpacks pretty quickly. If you're interested, I could update this post with the 1.12 version goes live, currently it's not public.

**Comment by Forstride** [comment]
I mean, having a compiled .jar doesn't help.  I'd need the unlocalized biome names.

**Comment by SirChamomile** [comment]
They aren't finalized yet, so I'll drop them in here when they are.

**Comment by SirChamomile** [comment]
I got the list of biomes names for you:

```
conquest:alder_swamp
conquest:bamboo_forest
conquest:beach_mod
conquest:birch_forest
conquest:bog
conquest:boreal_forest
conquest:cold_beach_mod
conquest:deciduous_forest
conquest:desert_mod
conquest:forest_flower_plain
conquest:japanese_forest
conquest:jungle_mod
conquest:lorein_forest
conquest:marsh
conquest:mediterranean
conquest:mega_boreal_forest
conquest:mesa_extreme_mod
conquest:moorland
conquest:mountains
conquest:ocean
conquest:oldgrowth_forest
conquest:red_desert
conquest:river
conquest:tundra
conquest:tundra_marsh
```

In case you're interested, the thread I'm referencing is here:

https://github.com/Conquest-Reforged/ConquestReforged/issues/55

**Comment by Forstride** [comment]
Are there images of said biomes?  Don't really wanna just add them based on the name alone.

**Comment by SirChamomile** [comment]
Here you go Forstride. I couldn't find a couple like the cold beach, but I got most of them. Let me know if you want any more information. I'll be happy to provide it.

[https://imgur.com/a/3L5hsjs](url)
