### ISSUE TITLE
Unable to Breed Turkeys & Deers Under Normal Circumstances

### ISSUE THREAD

**Issue by KarinaAE123** [Glitchfiend/FamiliarFauna#23]
Turkeys are un-breedable in Survival, but breedable in Creative. Deers are un-breedable in Creative, and I'm not sure about Survival as they're too skittish (though this is probably the intention). It should also be noted that it isn't always consistent. It's currently unknown to me if this a universal issue.

Video clip: [https://youtu.be/HD6XcVF7Jyo](url)

This issue should be looked into the next time the mod is updated.

**Comment by Forstride** [comment]
Turkey and deer have genders, and you can only breed one of them with the opposite gender.
