### ISSUE TITLE
Bug Net not working

### ISSUE THREAD

**Issue by BrennieBoo** [Glitchfiend/FamiliarFauna#25]
Minecraft: 1.12.2
Forge: 14.23.4.2705
Mods: Biomes o plenty, Familiar Fauna, Optifine HD E2, Serene Seasons, Tough as Nails.

Not sure if I need a newer forge but the bug net won't catch any bugs? I tried creative mode and survival mode.

**Comment by Forstride** [comment]
Do you have an empty bug habitat in your inventory?  And are you right clicking the bugs?

**Comment by BrennieBoo** [comment]
Yes and yes, but nothing is happening.

**Comment by Forstride** [comment]
And you're sure you're close enough/aiming directly at it?  The distance/hitbox can be a bit finicky at times.

**Comment by BrennieBoo** [comment]
Yes... Even when the butterfly was sitting still on the ground nothing happened.

**Comment by LukewarmYeti** [comment]
@BrennieBoo where you in creative mode? It works fine for me in survival, but the bug catcher doesn't work in creative - it can't catch anything.

**Comment by BrennieBoo** [comment]
> @BrennieBoo where you in creative mode? It works fine for me in survival, but the bug catcher doesn't work in creative - it can't catch anything.

They must have fixed it in the December release because it works now.
