### ISSUE TITLE
[Suggestion] Deers replace cow spawns

### ISSUE THREAD

**Issue by ColossusX13** [Glitchfiend/FamiliarFauna#29]
This is more of a personal preference than an issue but you should disable "replace cows with deer" by default. Most persons installing this mod do so for variety, not to lose vanilla spawns. Also I figure most persons don't dig through config files like I do so this would be easily overlooked until days later when they can't find any cows.

**Comment by Forstride** [comment]
No.  You can easily find cows still, just not in the biomes deer spawn in.
