### ISSUE TITLE
Butterfly death sounds

### ISSUE THREAD

**Issue by celittle3** [Glitchfiend/FamiliarFauna#32]
A config option to disable the butterfly death sounds. I love the butterflies, but we have a heavily modded server that has blocks/plants that the butterflies randomly run into causing their death. Its sad to hear the little lives end all the time.

**Comment by Forstride** [comment]
?  They don't have death sounds

**Comment by celittle3** [comment]
Hmmm Ok, thanks. I'll look into it more.
