### ISSUE TITLE
Allow spawn biome configuration for individual mobs

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/FamiliarFauna#4]
Self-explanatory

**Comment by drakray** [comment]
Maybe add support for biome property, like WET, COLD, etc?
This should allow for easy support of most biome from any mods that do their job correctly ;)

**Comment by Forstride** [comment]
Biome dictionary tags are often still too vague, and I imagine most people would rather have control over which individual biomes mobs spawn in.

**Comment by drakray** [comment]
ah okk, thank for the follow-up :)

**Comment by DarkMatterXCIX** [comment]
Would be awesome if you made a GUI, that allowed u to select any mob from any mod, and the ability to select which biomes that creature would be allowed to be in, and a OP permission in a server that when a op changes it, it goes into affect for server aswell?

**Comment by Forstride** [comment]
There are already mods that can change mob spawns for any mod AFAIK.  This is just going to be for mobs within Familiar Fauna as a convenience type thing.

And no, I'm not adding fish, since vanilla is adding them in 1.13

**Comment by DarkMatterXCIX** [comment]
well mods that do that aren't made well at all, infact I can pretty much say they don't work, the mods that add the feature to change what creatures spawn where, have to be changed in a config file and adding lets say a cow to spawn in BoP means i have to add that cow to each individual 80+ biomes added in, which is so so tedius and takes way to long especially with mods like Mo Creatures or Familier Fuana, which yes i do admit supports it automatically but not MoC, this isn't under your power I understand, but it is just way to tedius without a proper mod that has a GUI or a better config file that can change a entire mods spawning.
