### ISSUE TITLE
[Curseforge] Is 1.0.1 missing?

### ISSUE THREAD

**Issue by BrisingrAerowing** [Glitchfiend/FamiliarFauna#5]
Curseforge shows that there's a 1.0.1 version, but selecting it displays a 'File not found' page. Was the upload goofed, or is Curse being glitchy again?

**Comment by Forstride** [comment]
Works for me.  Probably just CurseForge acting up.

**Comment by BrisingrAerowing** [comment]
I found it was doing that for pretty much any file that was set to Alpha or Beta. Very annoying.
