### ISSUE TITLE
[Suggestion] Mob Drop

### ISSUE THREAD

**Issue by drakray** [Glitchfiend/FamiliarFauna#6]
Maybe make the Snail drop slimeball?
and I haven't tried yet, but are the venison meat oreDicted to listAllvenisonraw/cooked & foodVenisonraw/cooked for Harvestcraft compatibility?

**Comment by Forstride** [comment]
I thought about having snails drop slimeballs, but it always felt like an item that's supposed to be more rare, so IDK.  You can add it to the snail's loot table yourself if you really want it though.

As for venison, it has an ore dictionary listing for raw/cooked (Found in ModCrafting), but I don't know if it's the same as HarvestCraft's.  There isn't a standard for ore dictionary names for food AFAIK, as Forge doesn't include vanilla meats in it.

**Comment by Sunconure11** [comment]
I'd advise using listAllmeatraw and listAllmeatcooked for the venison entries.
