### ISSUE TITLE
Animals Shown as Hostile on Minimaps

### ISSUE THREAD

**Issue by Tomsnodgrass** [Glitchfiend/FamiliarFauna#7]
I'm using Xaero's Minimap Mod, and on there all mobs from this mod are shown as hostile creatures. I do not know if this is the same on other minimap mods

**Comment by BrisingrAerowing** [comment]
They display as hostile on JourneyMap as well.

**Comment by Forstride** [comment]
I accidentally had the entities implementing IMob instead of IAnimals.  Should be fixed in FF 1.0.2

**Comment by Forstride** [comment]
I recently made some changes to butterflies.  Can you guys let me know if this is still an issue or not in 1.0.3?
