### ISSUE TITLE
Butterflies are a bit too common.

### ISSUE THREAD

**Issue by BrisingrAerowing** [Glitchfiend/FamiliarFauna#8]
[Image](https://imgur.com/a/YRVNZ)

Yeah, I think the butterfly spawn rates are a tad too high. I've also seen a forest with a cloud of butterflies.

**Comment by Forstride** [comment]
I've lowered the default spawn weight from 2 to 1, but if that's still not to your liking, you can always just change the spawn settings yourself in the config file.
